---
title: "Logistic Regression - Data Science Capstone"
author: "Sai kumar miryala"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Introduction

### What is "method"?

This is an introduction to Kernel regression, which is a non-parametric
estimator that estimates the conditional expectation of two variables
which is random. The goal of a kernel regression is to discover the
non-linear relationship between two random variables. To discover the
non-linear relationship, kernel estimator or kernel smoothing is the
main method to estimate the curve for non-parametric statistics. In
kernel estimator, weight function is known as kernel function
[@efr2008]. Cite this paper [@bro2014principal]. The GEE [@wang2014].

This is my work and I want to add more work...

### Related work

This section is going to cover the literature review...

## Methods

## Research papers:

#Validation of prediction models based on lasso regression with multiply imputed data

The purpose of this paper is to evaluate and discuss the optimism in the discriminative performance of a lasso model for predicting dyspnea in Chronic Obstructive Pulmonary Disease (COPD) patients.

The study used a lasso model to predict dyspnea in Chronic Obstructive Pulmonary Disease patients. Researchers evaluated optimism by comparing four ways for handling multiply imputed data in the bootstrap procedure, which involved resampling completed datasets and incomplete datasets with further imputation.

The study focuses on the lasso model's optimistic discriminative performance as well as the sensitivity of optimism estimations to imputed data handling, showing the significance of precise model validation.

The results reveal optimistic discriminative performance and suboptimal calibration of the lasso model in predicting dyspnea in COPD patients.

#LASSO Regression Modeling on Prediction of Medical Terms among Seafarers’ Health Documents Using Tidy Text Mining.

The article may confront obstacles in analysing health data from seafarers, as well as potential biases and restrictions in generalising findings to other situations.

The paper's goal is to predict medical terms in seafarers' health papers using LASSO regression & tidy text mining, recognising the importance of the analysis of sentiment and adding to the creation of an Epidemiological Observatory of Seafarers' Pathologies and Injuries.

This research is important because it uses advanced approaches to forecast medical terminology in sailors' health records, hence improving medical judgements in remote maritime. It also helps to establish a framework for better understanding and controlling the health of seafarers.






### Statistical Modeling

```{r}

```

### Conclusion

## References
